[mesh]
ds = 0.001        # mesh spacing 
num_x = 101       # number of x grid points
num_y = 101       # number of y grid points

[save]
nstep = 100
directory = 'data'

[fluid]
kvisc   = 2.0e-4   # kinematic viscosity 
density = 1.0      # reference density  

[init]
type = 'constant'
velocity.x = 0.0
velocity.y = 0.0

[bndry.left]
#type = 'inflow'
#value = 0.1
type = 'noslip'

[bndry.right]
#type = 'outflow'
type = 'noslip'

[bndry.top]
#type = 'noslip'
type ='moving'
value = 0.1

[bndry.bottom]
type = 'noslip'

[stop]       
#cond  = "time"     # termination critera
cond  = "steady"    # termination critera
time  = 10.0        # simulation stop time
etol  = 1.0e-5      # error tolerance for steady state  (optional)
