[mesh]
ds = 0.01            
len_x = 1.0
len_y = 1.0

[save]
nstep = 100 
directory = 'data'

[fluid]
kvisc   = 2.0e-4     
density = 1.0        

[init]
type = 'constant'
velocity.x = 0.1
velocity.y = 0.0

[bndry.left]
type = 'inflow'
value = 0.1

[bndry.right]
type = 'outflow'

[bndry.top]
type ='noslip'

[bndry.bottom]
type = 'noslip'

[stop]       
cond  = "time"       
time  = 500.0         
