[mesh]
ds = 0.01          # mesh spacing
num_x = 101        # number of x grid points
num_y = 101        # number of y grid points

[fluid]
kvisc   = 1.0e-4   # kinematic viscosity 
density = 1.0      # reference density  

[stop]       
cond  = "time"      # termination critera
time  = 10.0        # simulation stop time
etol  = 1.0e-5      # error tolerance for steady state  (optional)

# Set rectangular domain boundary conditions
# options: inflow, outflow, noslip, slip

[boundary.left]
type = 'inflow'
velocity = 0.1

[boundary.right]
type = 'outflow'

[boundary.top]
type = 'noslip'

[boundary.bottom]
type = 'noslip'



